services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3009:3001"
    networks:
      - portfolio-network
    # volumes:
    #   - ./:/usr/src/app
    #   - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio
      MYSQL_USER: dannguyen
      MYSQL_PASSWORD: 17052002
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - $PWD/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - 3306
    networks:
      - portfolio-network
  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - 6379
    networks:
      - portfolio-network
    # volumes:
    #   - ./redis-data:/data
    restart: always
    command: redis-server --appendonly yes

networks:
  portfolio-network:
    driver: bridge